Controllers/ClasseController.cs
using Microsoft.AspNetCore.Mvc;

namespace Corso10157.Controllers
{
    public class ClasseController : Controller
    {
        [HttpGet]
        public IActionResult Index(string id)
        {
            ViewData["Title"] = "Classi";
            return View();
        }
    }
}

Controllers/CoursesController.cs
using System.Collections.Generic;
using System.Threading.Tasks;
using Corso10157.Models.Services.ADO.NET.Infrastructure;
using Corso10157.Models.Services.ADO.NET.InputModels;
using Corso10157.Models.ViewModel;
using Microsoft.AspNetCore.Mvc;
using System.Linq;
using Corso10157.Models.Exception;

namespace Corso10157.Controllers
{
    public class CoursesController : Controller
    {
        private readonly ICachedCourseService courseService;
        public CoursesController(ICachedCourseService courseService)
        {
            this.courseService = courseService;
        }

        [HttpGet]
        public async Task<IActionResult> Index(CourseListInputModel input)
        {
            ViewData["Title"] = "I Corsi";
            ListViewModel<CourseViewModel> courses = await courseService.GetCoursesAsync(input.Search, input.Page, input.OrderBy, input.Ascending, input.Limit, input.Offset);
            CourseListViewModel viewModel = new CourseListViewModel();
            viewModel.Courses = courses;
            viewModel.Input = input;
            return View(viewModel);
        }

        [HttpGet]
        public async Task<IActionResult> Detail(int id)
        {
            CourseDetailViewModel viewModel = await courseService.GetCourseAsync(id);
            ViewData["Title"] = $"Corso - {viewModel.NomeCorso}";
            return View(viewModel);
        }

        [HttpGet]
        public IActionResult Create()
        {
            ViewData["Title"] = "Crea Corso";
            var inputModel = new CourseCreateInputModel();
            return View(inputModel);
        }

        [HttpPost]
        public async Task<IActionResult> Create(CourseCreateInputModel inputModel)
        {
            if (!ModelState.IsValid)
            {
                try
                {
                    CourseDetailViewModel courese = await courseService.CreateCourseAsync(inputModel);
                    return RedirectToAction(nameof(Index));
                }
                catch (CourseNomeCorsoUnavalidTableException)
                {
                    ModelState.AddModelError(nameof(CourseDetailViewModel.NomeCorso), "Questo corso esiste già!");
                }
            }
            ViewData["Title"] = "Crea Corso";
            return View(inputModel);
        }

        public async Task<IActionResult> IsAvaibleNomecorso(string nomeCorso)
        {
            bool result = await courseService.IsAvaibleNomecorsoAsync(nomeCorso);
            return Json(result);
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>

    <link href="\Images\favicon.ico" rel="icon" type="image/x-icon" />
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css" integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous">

    <link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css" integrity="sha384-AYmEC3Yw5cVb3ZcuHtOA93w35dYTsvhLPVnYs9eStHfGJvOvKxVfELGroGkvsg+p" crossorigin="anonymous"/>

    <title>@ViewData["Title"]</title>
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">Corso10157</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <a class="nav-link" asp-action="Index" asp-controller="Home">Home</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" asp-action="Index" asp-controller="Classe">Classe</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" asp-action="Index" asp-controller="Courses">Corsi</a>
      </li>
          <li class="nav-item">
        <a class="nav-link" href="#">Implementare..</a>
      </li>
    </ul>
  
  </div>
</nav>

<div class="container">
    @RenderBody()
</div>

<footer>
  View di Layout - Fine
</footer>

<script src="https://code.jquery.com/jquery-3.5.1.min.js" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.min.js" integrity="sha384-+YQ4JLhjyBLPDQt//I+STsc9iw4uQqACwlvpslubQzn4u2UU2UFM80nGisd026JF" crossorigin="anonymous"></script>

@RenderSection("script", false)


</body>
</html>

Views/Shared/_Validation.cshtml
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.19.2/jquery.validate.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.19.2/additional-methods.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.19.2/localization/messages_it.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validation-unobtrusive/3.2.11/jquery.validate.unobtrusive.min.js"></script>