Controllers/CoursesController.cs
using System.Collections.Generic;
using System.Threading.Tasks;
using Corso10157.Models.Services.ADO.NET.Infrastructure;
using Corso10157.Models.Services.ADO.NET.InputModels;
using Corso10157.Models.ViewModel;
using Microsoft.AspNetCore.Mvc;
using System.Linq;
using Corso10157.Models.Exception;

namespace Corso10157.Controllers
{
    public class CoursesController : Controller
    {
        private readonly ICachedCourseService courseService;
        public CoursesController(ICachedCourseService courseService)
        {
            this.courseService = courseService;
        }

        [HttpGet]
        public async Task<IActionResult> Index(CourseListInputModel input)
        {
            ViewData["Title"] = "I Corsi";
            ListViewModel<CourseViewModel> courses = await courseService.GetCoursesAsync(input.Search, input.Page, input.OrderBy, input.Ascending, input.Limit, input.Offset);
            CourseListViewModel viewModel = new CourseListViewModel();
            viewModel.Courses = courses;
            viewModel.Input = input;
            return View(viewModel);
        }

        [HttpGet]
        public async Task<IActionResult> Detail(int id)
        {
            CourseDetailViewModel viewModel = await courseService.GetCourseAsync(id);
            ViewData["Title"] = $"Corso - {viewModel.NomeCorso}";
            return View(viewModel);
        }

        [HttpGet]
        public IActionResult Create()
        {
            ViewData["Title"] = "Crea Corso";
            var inputModel = new CourseCreateInputModel();
            return View(inputModel);
        }

        [HttpPost]
        public async Task<IActionResult> Create(CourseCreateInputModel inputModel)
        {
            if (!ModelState.IsValid)
            {
                try
                {
                    CourseDetailViewModel courese = await courseService.CreateCourseAsync(inputModel);
                    return RedirectToAction(nameof(Index));
                }
                catch (CourseNomeCorsoUnavalidTableException)
                {
                    ModelState.AddModelError(nameof(CourseDetailViewModel.NomeCorso), "Questo corso esiste già!");
                }
            }
            ViewData["Title"] = "Crea Corso";
            return View(inputModel);
        }

        public async Task<IActionResult> IsAvaibleNomecorso(string nomeCorso)
        {
            bool result = await courseService.IsAvaibleNomecorsoAsync(nomeCorso);
            return Json(result);
        }
    }
}

Customizations/ViewComponents/PaginationBarViewComponent.cs
using Corso10157.Models.ViewModel;
using Corso10157.Models.ViewModel.Interfaces;
using Microsoft.AspNetCore.Mvc;

namespace Corso10157.Customizations.ViewComponents
{
    public class PaginationBarViewComponent : ViewComponent
    {
        public IViewComponentResult Invoke(IPaginationInfo model)
        {
            return View(model);
        }
    }
}

Views/Courses/Create.cshtml
@model CourseCreateInputModel

<h1>@ViewData["Title"]</h1>

<form method="post">
    <div class="row">
        <div class="col-sm-8">
            
            <input type="text" asp-for="NomeCorso" class="form-control form-control-lg" placeholder="Titolo del Corso..." />
            <span class="text-danger"  asp-validation-for="NomeCorso"></span>
        </div>
        <div class="col-sm-4">
            <button type="submit" class="btn btn-primary btn-lg btn-block"><i class="fas fa-rocket"></i> Crea Corso!</button>
            <div asp-validation-summary="All" class="text-danger"></div>
        </div>
    </div>
</form>

@section script{
    <partial name="_Validation"></partial>
}

Views/Courses/Detail.cshtml
@model CourseDetailViewModel

<div class="row">
    <div class="col-sm-9">
        <h1>@Model.NomeCorso</h1>
        <h5>di @Model.Autore</h5>
        <p>@Model.DescrizioneDettagliata</p>

    </div>
    <div class="col-sm-3">
        <img src="/images/@Model.Image" class="img-fluid w-100"alt="Img Corso">
        <div>@Model.Prezzo</div>
    </div>
</div>
    <div class="row">
        <div class="col-sm-12">
            <h4>@Model.Lezioni.Count Lezioni</h4>
        </div>
    </div>
@foreach (var item in @Model.Lezioni)
{
        <div class="row">
            <div class="col-sm-9">
                @item.Titolo
            </div>
            <div class="colsm-3">
                @item.Durata
            </div>
        </div>
        <hr>
}
<div class="row">
    <div class="col-sm-9">
        <i>Totale</i>
    </div>
    <div class="col-sm-3">
        @Model.Totale
    </div>
</div>
<div class="row">
    <div class="col-sm-12 text-center">
<a class="btn btn-secondary" asp-controller="Courses" asp-action="Index">Torna ai corsi</a>
    </div>
</div>

Views/Courses/Index.cshtml
@model CourseListViewModel
    <div class="row">
        <div class="col-sm-6">
            <h2>Elenco Corsi
                <a class="btn btn-outline-primary btn-sm" asp-controller="Courses" asp-action="Create">
                    <i class="fa fa-plus"></i> Nuovo
                </a>
            </h2>
        </div>
        <div class="col-sm-6">
            <form class="form-inline my-2 my-lg-0" asp-action="Index" asp-controller="Courses" method="get">
                <input class="form-control mr-sm-2" type="text" name="search" placeholder="Ricerca..." aria-label="Cerca" value="@Model.Input.Search" />
                <button class="btn btn-outline-success my-2 my-sm-0"><i class="fas fa-search"></i></button>
            </form>
        </div>
    </div>

<div class="container mt-5">
    <div class="col-sm-12">
        <nav aria-label="Page navigation text-center">
            <ul class="pagination">
                <li class="page-item" aria-current="page">
                    <a class="page-link" asp-route-orderby="NomeCorso" asp-route-ascending="@(Model.Input.OrderBy == "NomeCorso" ? !Model.Input.Ascending : true)" asp-route-search="@Model.Input.Search">Ordina per Nome @if (Model.Input.OrderBy == "NomeCorso")
                        {
                                            <i class="fas fa-caret-@(Model.Input.Ascending ? "up" : "down")"></i>
                        }
                    </a>
                </li>
                <li class="page-item">
                    <a class="page-link" asp-route-orderby="Prezzo" asp-route-ascending="@(Model.Input.OrderBy == "Prezzo" ? !Model.Input.Ascending : true)" asp-route-search="@Model.Input.Search">Ordina per Prezzo  @if (Model.Input.OrderBy == "Prezzo")
                        {
                                            <i class="fas fa-caret-@(Model.Input.Ascending ? "up" : "down")"></i>
                        }
                    </a>
                </li>
                <li class="page-item">
                    <a class="page-link" asp-route-orderby="Rating" asp-route-ascending="@(Model.Input.OrderBy == "Rating" ? !Model.Input.Ascending : true)" asp-route-search="@Model.Input.Search">Ordina per Rating  @if (Model.Input.OrderBy == "Rating")
                        {
                                            <i class="fas fa-caret-@(Model.Input.Ascending ? "up" : "down")"></i>
                        }
                    </a>
                </li>
            </ul>
        </nav>
    </div>
</div>
@foreach (CourseViewModel course in Model.Courses.Result)
{
        @* <div class="row">
        <div class="col-sm-7">
        <h3>@course.NomeCorso</h3>
        <div class="author">di @course.Autore</div>
        <p>@course.Descrizione</p>
        <div class="prezzo">&euro; @course.Prezzo</div>
        </div>
        <div class="col-sm-2">

        <rating value="@course.Rating"></rating>
        </div>
        <div class="col-sm-3">
        <img src="~/Images/@course.Image" alt="Img del corso" class="img-fluid" heigth="250px" width="250px">
        <a asp-controller="Courses" asp-action="Detail" asp-route-id="@course.Id" class="btn btn-warning">Dettaglio</a>
        </div>
        </div>
        <hr> *@
    <partial name ="Courses\_CourseLine" model="@course"></partial>
}

<vc:pagination-bar model="@Model"></vc:pagination-bar>